### ISSUE TITLE
Is ROracle being envoked?

### ISSUE THREAD

**Issue by odaniel1** [moj-analytical-services/oracleConnectR#5]
Since the code has been adapted to use either `ROracle` or `odbc` to connect to the server, clues have pointed towards the idea that the call to `ROracle` is failing.

We need to understand whether there is a bug which is causing the call to ROracle to fail.

Possible approaches to debugging include:

* First checking whether the function `create_ROracle_connection ` works as expected.

* If that works, then looking at how the function behaves when called within `try` [here](https://github.com/moj-analytical-services/oracleConnectR/blob/380a5d3986e4fbb1b5fc3620a8c6bff4f53ef3aa/R/connections.R#L17).

**Comment by odaniel1** [comment]
@beatricenixon  - Picking up on your solutions/queries, and adding to the GitHub issue as its a really useful reference for future!

----

**Email 01/02/2020:**

The line 
```drv <- DBI::dbDriver("Oracle")```

in the create_ROracle_connection  function produces an error message unless the library ROracle has already been loaded. I’ve therefore added in a line to the function to load ROracle if it’s installed:

```
  # Load ROracle library if already installed
  if("ROracle" %in% rownames(installed.packages()) == TRUE){
    library("ROracle")
  }
```
----

**Email 02/02/2020:**
I’ve been reading about the differences between depends and imports this morning in order to fix the DBI issue you raised on GitHub.
https://r-pkgs.org/namespace.html#namespace

However as I was reading I came across this line: *You should never use require() or library() in a package: instead, use the Depends or Imports fields in the DESCRIPTION.*

----

I vaguely remember battling this when I was designing the functionality - eg. how can I conditionally load a package only if the user has it.

I don't know the solution, but it might be that in the case of ROracle [this SO answer](https://stackoverflow.com/a/61988897/829967) provides a  workaround by loading the package name space, and not the entire package, and then piecing this together with the guidance you linked to before, it might be that we can get away with using `requireNamespace()`

```
  # Load ROracle library if already installed
  if("ROracle" %in% rownames(installed.packages()) == TRUE){
    requireNamespace("ROracle")
  }
```

The guidance you linked to above implies that using `requireNamespace()` within a package is safe/good practice - if this fails and we need to use `loadNamespace()` then the guidance is at least softer than its position on `library()`: saying only that you never *need to use* `loadNamespace()` rather than **should never use** `library()`.

**Comment by odaniel1** [comment]
In fact - reading a bit more, I don't think this even needs to be inside an if statement; this table from the guidance indicates that the function will just return the value `FALSE` if Roracle is not installed.

  | Throws error | Returns FALSE
-- | -- | --
Load | loadNamespace("x") | requireNamespace("x", quietly = TRUE)
Attach | library(x) | require(x, quietly = TRUE)

One way to test this behaviour would be in testing to add a requirement on some dummy package you don't have installed and see what the behaviour is, eg. just adding a random `requireNamespace("llamaR", quietly = TRUE)` somewhere and seeing if it just gets ignored

**Comment by beatricenixon** [comment]
I had a play with requireNamespace("ROracle", quietly = TRUE) this morning. When I ran it on it's own in the console nothing was outputted, however when I assigned it to an object e.g. ROracle_available <- requireNamespace("ROracle", quietly = TRUE) then ROracle_available has a value of TRUE or FALSE depending on whether ROracle is installed.

I wondered about having this as the ifelse condition in the create_connection function instead of the try( ). 
E.g. If (requireNamespace("ROracle", quietly = TRUE) == TRUE) then run con <- create_ROracle_connection(db_name, config_path), silent = TRUE) otherwise try the odbc link.
I could then have a line in create_ROracle_connection function for loading ROracle, without the need for an ifelse. I guess the loading of ROracle would have to be through loadNamespace("ROracle") instead of library("ROracle"). 

I'll give this a go and see where I get to.
